name: CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["16", "latest"]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install xvfb for headless browser testing
        run: sudo apt-get install -y xvfb

      - name: Setup Node.js (${{ matrix.node-version }})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: xvfb-run npm run test

  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm ci
      - run: npm install --global vsce
      - run: vsce package
      - uses: actions/upload-artifact@v3
        with:
          name: vsix-file
          path: |
            vscode-stable-sort-*.vsix

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/download-artifact@v1
        with:
          name: vsix-file
          path: dist

      - name: Publish to Visual Studio Marketplace
        if: "startsWith(github.ref, 'refs/tags/')"
        run: npx vsce publish --pat ${{ secrets.VSMARKETPLACE_TOKEN }} --packagePath ./dist/vscode-stable-sort-*.vsix
        timeout-minutes: 5

      - name: Publish to Open VSX Repository
        if: "startsWith(github.ref, 'refs/tags/')"
        run: npx ovsx publish --pat ${{ secrets.OPENVSX_TOKEN }} --packagePath ./dist/vscode-stable-sort-*.vsix
        timeout-minutes: 5
