name: Release
on:
  workflow_dispatch:
  create:
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Download already built package files
        uses: actions/download-artifact@v1
        with:
          name: vsix-file
          path: dist

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Install vsce and ovsx
        run: npm install --save-dev @vscode/vsce ovsx

      - name: (Visual Studio Marketplace) Login
        run: echo ${{ secrets.VSMARKETPLACE_TOKEN }} | vsce login sgryjp

      - name: (Visual Studio Marketplace) Publish
        run: npx vsce publish --packagePath ./dist/vscode-stable-sort-*.vsix
        timeout-minutes: 5

      - name: (Open VSX Repository) Publish
        run: npx ovsx publish --pat ${{ secrets.OPENVSX_TOKEN }} --packagePath ./dist/vscode-stable-sort-*.vsix
        timeout-minutes: 5
