name: Release
on:
  workflow_dispatch:
  create:
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/download-artifact@v1
        with:
          name: vsix-file
          path: dist

      - name: (Visual Studio Marketplace) Install vsce
        if: "startsWith(github.ref, 'refs/tags/')"
        run: npm install -g @vscode/vsce

      - name: (Visual Studio Marketplace) Login
        if: "startsWith(github.ref, 'refs/tags/')"
        run: echo ${{ secrets.VSMARKETPLACE_TOKEN }} | vsce login sgryjp

      - name: (Visual Studio Marketplace) Publish
        if: "startsWith(github.ref, 'refs/tags/')"
        run: vsce publish --packagePath ./dist/vscode-stable-sort-*.vsix
        timeout-minutes: 5

      - name: (Open VSX Repository) Publish
        if: "startsWith(github.ref, 'refs/tags/')"
        run: npx ovsx@latest publish --pat ${{ secrets.OPENVSX_TOKEN }} --packagePath ./dist/vscode-stable-sort-*.vsix
        timeout-minutes: 5
